<?php

namespace App\Http\Responses;

enum ErrorCode: string
{
    case GEN_FORBIDDEN = 'GEN-FORBIDDEN';
    case GEN_API_ERROR = 'GEN-API-ERROR';
    case GEN_NOT_FOUND = 'GEN-NOT-FOUND';
    case GEN_UNAUTHORIZED = 'GEN-UNAUTHORIZED';
    case GEN_WRONG_ARGS = 'GEN-WRONG-ARGS';
    case FEATURE_NOT_ALLOWED = 'FEATURE-NOT-ALLOWED';
    case REACH_PLAN_LIMIT = 'REACH-PLAN-LIMIT';
    case REACH_PLAN_STORAGE_LIMIT = 'REACH-PLAN-STORAGE-LIMIT';
    case REACH_PLAN_PUBLISH_LIMIT = 'REACH-PLAN-PUBLISH-LIMIT';
    case REACH_PLAN_PUBLISH_WEEKS_LIMIT = 'REACH-PLAN-PUBLISH-WEEKS_LIMIT';
    case INSUFFICIENT_CREDITS = 'INSUFFICIENT-CREDITS';
}
