<x-emails.main>
    <x-emails.banner name="{{ $user->name }}"/>
    <!-- Email content -->
    <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" height="auto"
           style="border-collapse:collapse">
        <tbody>
        <tr>
            <td align="center" valign="center" style="text-align:center; padding-bottom: 10px; padding: 30px 60px;">
                <!-- Email content -->
                <div style="text-align:left;">
                    <p style="line-height: 1.6;">
                        Great news! Your video "<b>{{ $video->title }}</b>" is now ready for you to
                        enjoy.
                    </p>

                    <a href="{{ $video_url }}" target="_blank"
                       style="text-decoration: none; background: #1886FF; color: #fff; padding: 15px 20px; display: inline-block; border-radius: 6px; ">
                        View video
                    </a>

                    <a href="{{ $destination_url }}" target="_blank"
                       style="text-decoration: none; background: #1886FF; color: #fff; padding: 15px 20px; display: inline-block; border-radius: 6px;">
                        Explore Syllaby
                    </a>

                    <p style="line-height: 1.7;">Best Regards , <br> Syllaby team</p>

                    @if (filled($related_topics))
                        <div>
                            <p style="font-weight: bold; font-size: 18px;">
                               Next Video Ideas
                            </p>

                            <ul style="line-height: 1.4;">
                                @foreach ($related_topics as $topic)
                                    <li> {{ $topic }}</li>
                                @endforeach
                            </ul>
                            
                            <a href="{{ $destination_url }}" target="_blank" style="font-weight: bold; text-decoration: none; color: #1886FF; display: block;">
                                Start Creating ⟶
                            </a>

                            <p style="font-size: 12px; color: #666; font-style: italic;">
                                <strong>Disclaimer:</strong> These suggestions were generated by AI based on your previous topics. 
                                Feel free to use them as inspiration or come up with your own unique ideas!
                            </p>
                        </div>
                    @endif
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</x-emails.main>
